-- ============================================
-- Migration: ECOX Audit Trail & Creator Notifications
-- Fecha: 2025-11-27
-- Descripción: Infraestructura forense ECOX + Notificaciones al creador
-- ============================================

-- ============================================
-- PARTE 1: TABLA ECOX AUDIT TRAIL (Trazabilidad Forense)
-- ============================================
-- Esta tabla es el corazón de la evidencia forense de EcoSign
-- Registra CADA paso del firmante desde que abre el link hasta que firma

CREATE TABLE IF NOT EXISTS public.ecox_audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Referencias
    workflow_id UUID REFERENCES public.signature_workflows(id) ON DELETE CASCADE NOT NULL,
    signer_id UUID REFERENCES public.workflow_signers(id) ON DELETE CASCADE NOT NULL,

    -- Timestamps
    event_timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Tipo de Evento
    event_type TEXT NOT NULL CHECK (event_type IN (
        'access_link_opened',        -- El firmante abrió el link de firma
        'nda_accepted',              -- Aceptó el NDA
        'mfa_challenged',            -- Se le presentó el desafío MFA
        'mfa_success',               -- MFA completado exitosamente
        'mfa_failed',                -- MFA falló
        'document_decrypted',        -- Documento descifrado y mostrado
        'document_viewed',           -- Firmante vio el documento
        'signature_started',         -- Empezó el proceso de firma (dibujando/escribiendo)
        'signature_applied',         -- Firma aplicada al documento
        'signature_completed',       -- Proceso de firma completado
        'eco_downloaded'             -- Descargó el certificado .ECO
    )),

    -- Datos de Contexto (Evidencia Forense)
    source_ip INET,                  -- IP del firmante
    user_agent TEXT,                 -- Navegador/Dispositivo
    geolocation JSONB,               -- { "country": "AR", "city": "Buenos Aires", "lat": -34.6037, "lon": -58.3816 }

    -- Detalles Específicos del Evento (Flexible)
    details JSONB,                   -- Información adicional específica por evento

    -- Smart Hash en el momento del evento (si aplica)
    document_hash_snapshot TEXT,     -- Hash del documento en ese momento

    -- Índices para búsquedas rápidas
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para rendimiento
CREATE INDEX IF NOT EXISTS idx_ecox_workflow_id ON public.ecox_audit_trail(workflow_id);
CREATE INDEX IF NOT EXISTS idx_ecox_signer_id ON public.ecox_audit_trail(signer_id);
CREATE INDEX IF NOT EXISTS idx_ecox_event_type ON public.ecox_audit_trail(event_type);
CREATE INDEX IF NOT EXISTS idx_ecox_event_timestamp ON public.ecox_audit_trail(event_timestamp DESC);

-- Comentarios
COMMENT ON TABLE public.ecox_audit_trail IS 'Registro forense completo de cada acción del firmante - Base del certificado ECOX';
COMMENT ON COLUMN public.ecox_audit_trail.event_type IS 'Tipo de evento en el flujo de firma';
COMMENT ON COLUMN public.ecox_audit_trail.details IS 'JSON con datos específicos: { "mfa_method": "TOTP", "time_to_decrypt_ms": 200, "signature_coords": {...} }';
COMMENT ON COLUMN public.ecox_audit_trail.document_hash_snapshot IS 'Hash del documento en el momento del evento (para verificación temporal)';

-- ============================================
-- PARTE 2: RLS (Row Level Security) para ECOX
-- ============================================
ALTER TABLE public.ecox_audit_trail ENABLE ROW LEVEL SECURITY;

-- Policy: Los owners pueden ver el audit trail de sus workflows
CREATE POLICY "Owners can view their workflow audit trails"
ON public.ecox_audit_trail
FOR SELECT
USING (
    workflow_id IN (
        SELECT id FROM public.signature_workflows
        WHERE owner_id = auth.uid()
    )
);

-- Policy: Los firmantes pueden ver su propio audit trail
CREATE POLICY "Signers can view their own audit trail"
ON public.ecox_audit_trail
FOR SELECT
USING (
    signer_id IN (
        SELECT id FROM public.workflow_signers
        WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
    )
);

-- Policy: La aplicación (service_role) puede insertar eventos
CREATE POLICY "Service role can insert audit events"
ON public.ecox_audit_trail
FOR INSERT
WITH CHECK (true);

-- ============================================
-- PARTE 3: FUNCIÓN PARA REGISTRAR EVENTOS ECOX
-- ============================================
-- Función auxiliar que la aplicación puede llamar desde Edge Functions
CREATE OR REPLACE FUNCTION public.log_ecox_event(
    p_workflow_id UUID,
    p_signer_id UUID,
    p_event_type TEXT,
    p_source_ip INET DEFAULT NULL,
    p_user_agent TEXT DEFAULT NULL,
    p_geolocation JSONB DEFAULT NULL,
    p_details JSONB DEFAULT NULL,
    p_document_hash_snapshot TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_event_id UUID;
BEGIN
    INSERT INTO public.ecox_audit_trail (
        workflow_id,
        signer_id,
        event_type,
        source_ip,
        user_agent,
        geolocation,
        details,
        document_hash_snapshot
    ) VALUES (
        p_workflow_id,
        p_signer_id,
        p_event_type,
        p_source_ip,
        p_user_agent,
        p_geolocation,
        p_details,
        p_document_hash_snapshot
    )
    RETURNING id INTO v_event_id;

    RETURN v_event_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.log_ecox_event IS 'Registra un evento en el audit trail ECOX desde la aplicación';

-- ============================================
-- PARTE 4: TRIGGER PARA NOTIFICAR AL CREADOR CUANDO ALGUIEN FIRMA
-- ============================================
-- Este trigger se activa cuando un firmante completa su firma
-- y notifica al owner (creador del workflow)

CREATE OR REPLACE FUNCTION notify_creator_on_signature()
RETURNS TRIGGER AS $$
DECLARE
  workflow_title TEXT;
  owner_email TEXT;
  owner_name TEXT;
  current_hash TEXT;
BEGIN
  -- Solo ejecutar si el estado cambió a 'signed'
  IF NEW.status = 'signed' AND (OLD.status IS NULL OR OLD.status != 'signed') THEN

    -- Obtener información del workflow y owner
    SELECT
      sw.original_filename,
      u.email,
      COALESCE(u.raw_user_meta_data->>'name', split_part(u.email, '@', 1)),
      sw.document_hash
    INTO workflow_title, owner_email, owner_name, current_hash
    FROM signature_workflows sw
    LEFT JOIN auth.users u ON u.id = sw.owner_id
    WHERE sw.id = NEW.workflow_id;

    -- Insertar notificación adicional para el creador (diferente al que ya existe)
    -- Este email tiene más detalles técnicos para el owner
    INSERT INTO workflow_notifications (
      workflow_id,
      recipient_email,
      recipient_type,
      signer_id,
      notification_type,
      subject,
      body_html,
      delivery_status
    ) VALUES (
      NEW.workflow_id,
      owner_email,
      'owner',
      NEW.id,
      'creator_detailed_notification',
      '🔔 Nueva Firma Recibida: ' || COALESCE(NEW.name, 'Usuario') || ' firmó ' || workflow_title,
      format(
        '<html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #111827;">Nueva Firma Registrada</h1>

          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="margin-top: 0;">Detalles de la Firma</h2>
            <p><strong>Firmante:</strong> %s (%s)</p>
            <p><strong>Documento:</strong> %s</p>
            <p><strong>Fecha y Hora:</strong> %s</p>
            <p><strong>Smart Hash:</strong> <code style="background: white; padding: 4px 8px; border-radius: 4px; font-size: 12px;">%s</code></p>
          </div>

          <div style="margin: 30px 0;">
            <p>Esta firma ha sido registrada con evidencia forense completa en el sistema ECOX.</p>
            <p>Puedes verificar el estado completo del documento en tu dashboard.</p>
          </div>

          <a href="https://app.ecosign.app/dashboard/workflows/%s"
             style="display: inline-block; background-color: #111827; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
            Ver Detalles del Workflow
          </a>

          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280;">
            <p>Este es un email automático del sistema EcoSign.</p>
            <p>La certeza forense de esta firma está respaldada por el registro ECOX completo.</p>
          </div>
        </body>
        </html>',
        COALESCE(NEW.name, 'Usuario sin nombre'),
        NEW.email,
        workflow_title,
        to_char(NOW(), 'DD/MM/YYYY HH24:MI:SS UTC'),
        COALESCE(current_hash, 'Pendiente de cálculo'),
        NEW.workflow_id
      ),
      'pending'
    );

    RAISE NOTICE 'Notificación detallada para creador enviada: workflow % - firmante %', NEW.workflow_id, NEW.email;

  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para notificar al creador
DROP TRIGGER IF EXISTS on_signature_notify_creator ON workflow_signers;
CREATE TRIGGER on_signature_notify_creator
  AFTER UPDATE ON workflow_signers
  FOR EACH ROW
  WHEN (NEW.status = 'signed')
  EXECUTE FUNCTION notify_creator_on_signature();

COMMENT ON FUNCTION notify_creator_on_signature IS 'Notifica al creador cuando un firmante completa su firma con detalles técnicos';

-- ============================================
-- PARTE 5: FUNCIÓN PARA GENERAR ECOX COMPLETO
-- ============================================
-- Esta función genera el contenido completo del certificado ECOX
-- para un workflow completado

CREATE OR REPLACE FUNCTION public.generate_ecox_certificate(p_workflow_id UUID)
RETURNS JSONB AS $$
DECLARE
    v_workflow RECORD;
    v_signers JSONB;
    v_audit_trail JSONB;
    v_result JSONB;
BEGIN
    -- Obtener datos del workflow
    SELECT
        sw.original_filename,
        sw.document_hash,
        sw.status,
        sw.created_at,
        sw.completed_at,
        u.email as owner_email,
        u.raw_user_meta_data->>'name' as owner_name
    INTO v_workflow
    FROM signature_workflows sw
    LEFT JOIN auth.users u ON u.id = sw.owner_id
    WHERE sw.id = p_workflow_id;

    IF v_workflow IS NULL THEN
        RAISE EXCEPTION 'Workflow % no encontrado', p_workflow_id;
    END IF;

    -- Obtener todos los firmantes
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', ws.id,
            'name', ws.name,
            'email', ws.email,
            'signing_order', ws.signing_order,
            'signed_at', ws.signed_at,
            'signature_hash', ws.signature_hash,
            'signature_data', ws.signature_data
        )
        ORDER BY ws.signing_order
    )
    INTO v_signers
    FROM workflow_signers ws
    WHERE ws.workflow_id = p_workflow_id
      AND ws.status = 'signed';

    -- Obtener todo el audit trail
    SELECT jsonb_agg(
        jsonb_build_object(
            'timestamp', eat.event_timestamp,
            'event_type', eat.event_type,
            'signer_id', eat.signer_id,
            'source_ip', host(eat.source_ip),
            'user_agent', eat.user_agent,
            'geolocation', eat.geolocation,
            'details', eat.details,
            'document_hash_snapshot', eat.document_hash_snapshot
        )
        ORDER BY eat.event_timestamp
    )
    INTO v_audit_trail
    FROM ecox_audit_trail eat
    WHERE eat.workflow_id = p_workflow_id;

    -- Construir el certificado ECOX completo
    v_result := jsonb_build_object(
        'ecox_version', '1.0',
        'generated_at', now(),
        'workflow', jsonb_build_object(
            'id', p_workflow_id,
            'document_name', v_workflow.original_filename,
            'final_hash', v_workflow.document_hash,
            'status', v_workflow.status,
            'created_at', v_workflow.created_at,
            'completed_at', v_workflow.completed_at,
            'owner', jsonb_build_object(
                'email', v_workflow.owner_email,
                'name', v_workflow.owner_name
            )
        ),
        'signers', COALESCE(v_signers, '[]'::jsonb),
        'audit_trail', COALESCE(v_audit_trail, '[]'::jsonb),
        'verification', jsonb_build_object(
            'total_events', (SELECT COUNT(*) FROM ecox_audit_trail WHERE workflow_id = p_workflow_id),
            'total_signers', (SELECT COUNT(*) FROM workflow_signers WHERE workflow_id = p_workflow_id AND status = 'signed'),
            'cryptographic_proof', v_workflow.document_hash,
            'verified_at', now()
        )
    );

    RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.generate_ecox_certificate IS 'Genera el certificado ECOX completo con toda la evidencia forense del workflow';

-- ============================================
-- PARTE 6: VISTA PARA DASHBOARD (Resumen de Audit Trail)
-- ============================================
CREATE OR REPLACE VIEW public.ecox_summary AS
SELECT
    sw.id as workflow_id,
    sw.original_filename,
    sw.status as workflow_status,
    COUNT(DISTINCT eat.signer_id) as unique_signers_with_activity,
    COUNT(eat.id) as total_events,
    MIN(eat.event_timestamp) as first_event_at,
    MAX(eat.event_timestamp) as last_event_at,
    jsonb_object_agg(
        eat.event_type,
        (SELECT COUNT(*) FROM ecox_audit_trail WHERE workflow_id = sw.id AND event_type = eat.event_type)
    ) as events_by_type
FROM signature_workflows sw
LEFT JOIN ecox_audit_trail eat ON eat.workflow_id = sw.id
GROUP BY sw.id, sw.original_filename, sw.status;

COMMENT ON VIEW public.ecox_summary IS 'Resumen ejecutivo del audit trail ECOX por workflow';

-- ============================================
-- FIN DE MIGRACIÓN
-- ============================================
